-- Drop the existing expenses table (WARNING: This deletes all expense data)
DROP TABLE IF EXISTS public.expenses;

-- Re-create the expenses table WITHOUT 'ON DELETE CASCADE'
create table expenses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Link to Auth User
  member_id bigint references members(id) not null, -- No cascade, safe for reassignment
  member_name text not null,
  category text not null,
  amount decimal(10,2) not null,
  note text,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table expenses enable row level security;

-- Policies for Expenses

-- Users can only see their own expenses
create policy "Users can view their own expenses"
  on expenses for select
  using (auth.uid() = user_id);

-- Users can only insert their own expenses
create policy "Users can insert their own expenses"
  on expenses for insert
  with check (auth.uid() = user_id);

-- Users can only update their own expenses
create policy "Users can update their own expenses"
  on expenses for update
  using (auth.uid() = user_id);

-- Users can only delete their own expenses
create policy "Users can delete their own expenses"
  on expenses for delete
  using (auth.uid() = user_id);
