-- Create table for members
create table members (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Link to Auth User
  name text not null,
  role text check (role in ('Admin', 'Member')) not null default 'Member',
  email text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create table for expenses
create table expenses (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null, -- Link to Auth User
  member_id bigint references members(id) on delete cascade not null,
  member_name text not null, -- Denormalized for simpler queries
  category text not null,
  amount decimal(10,2) not null,
  note text,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table members enable row level security;
alter table expenses enable row level security;

-- Policies for Members
-- Users can only see their own members
create policy "Users can view their own members"
  on members for select
  using (auth.uid() = user_id);

-- Users can only insert their own members
create policy "Users can insert their own members"
  on members for insert
  with check (auth.uid() = user_id);

-- Users can only update their own members
create policy "Users can update their own members"
  on members for update
  using (auth.uid() = user_id);

-- Users can only delete their own members
create policy "Users can delete their own members"
  on members for delete
  using (auth.uid() = user_id);

-- Policies for Expenses
-- Users can only see their own expenses
create policy "Users can view their own expenses"
  on expenses for select
  using (auth.uid() = user_id);

-- Users can only insert their own expenses
create policy "Users can insert their own expenses"
  on expenses for insert
  with check (auth.uid() = user_id);

-- Users can only update their own expenses
create policy "Users can update their own expenses"
  on expenses for update
  using (auth.uid() = user_id);

-- Users can only delete their own expenses
create policy "Users can delete their own expenses"
  on expenses for delete
  using (auth.uid() = user_id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.members (user_id, name, email, role)
  values (
    new.id, 
    coalesce(
      new.raw_user_meta_data->>'full_name', 
      new.raw_user_meta_data->>'name', 
      split_part(new.email, '@', 1), 
      'Member'
    ), 
    new.email, 
    'Admin'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
